### ISSUE TITLE
`plain-txt-passwd` should be `plain_text_passwd`

### ISSUE THREAD

**Issue by vpanteleev-sym** [shantanoo-desai/packer-ubuntu-server-uefi#11]
Thank you for the blog post. I noticed the error above. It occurs both in the blog post and this repository.

Hope this helps.

**Comment by vpanteleev-sym** [comment]
Hi, it is `text` not `txt`. Hope this helps.

**Comment by shantanoo-desai** [comment]
@VPanteleev-S7 Ah gotcha, I went through the documentation and you are right. Let me correct it.
