### ISSUE TITLE
afer install and reboot, cd install begins again

### ISSUE THREAD

**Issue by dgttm** [shantanoo-desai/packer-ubuntu-server-uefi#3]
thanks for your work.

I guess packer is again booting from iso instead of automatically booting from disk. 

If I manually select the second option, installation resumes.

![image](https://user-images.githubusercontent.com/13033378/232803556-e391269a-b7b8-414d-b1f6-b317ff77b975.png)

any hints?

cheers

Nicolas

**Comment by shantanoo-desai** [comment]
Hi @dgttm maybe check out this issue #2 I think this might depend on the `bootefimgr` sequence also for your case. Are you generating an image locally ?

You might have to check `sudo efibootmgr -v` in order to determine the boot sequence and adapt your `cloud-init/user-data` file accordingly

**Comment by shantanoo-desai** [comment]
@dgttm any updates?
